version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      npm-packages:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/wasm"
    schedule:
      interval: "monthly"
    groups:
      go-packages:
        patterns:
          - "*"

