name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'wasm/go.mod'

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 'latest'

      - name: Run Go unit tests in WebAssembly
        working-directory: wasm
        run: |
          go generate ./...
          GOOS=js GOARCH=wasm go test -exec="$(go env GOROOT)/lib/wasm/go_js_wasm_exec" ./...

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 'latest'

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'wasm/go.mod'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
